-- Enable the pg_graphql extension (optional but useful)
create extension if not exists pg_graphql;

-- Create leads table (for contact form submissions)
create table if not exists public.leads (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text,
  phone text, -- Optional field for future use
  service_type text, -- Optional field for future use
  budget text, -- Optional field for future use
  timeline text -- Optional field for future use
);

-- Create projects table (for portfolio items)
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text not null,
  metric text,
  image text, -- CSS class or image URL
  client text,
  year text,
  services text[], -- Array of strings
  challenge text,
  solution text,
  results text[], -- Array of strings
  testimonial jsonb -- Object with { text, author }
);

-- Enable Row Level Security (RLS)
alter table public.leads enable row level security;
alter table public.projects enable row level security;

-- Create policies for leads
-- Allow public access to insert leads (contact form)
create policy "Public leads can be created"
  on public.leads for insert
  with check (true);

-- Allow only authenticated users (admins) to view leads
create policy "Admins can view leads"
  on public.leads for select
  using (auth.role() = 'authenticated');

-- Create policies for projects
-- Allow public access to view projects
create policy "Public projects are viewable"
  on public.projects for select
  using (true);

-- Allow only authenticated users (admins) to insert, update, delete projects
create policy "Admins can insert projects"
  on public.projects for insert
  with check (auth.role() = 'authenticated');

create policy "Admins can update projects"
  on public.projects for update
  using (auth.role() = 'authenticated');

create policy "Admins can delete projects"
  on public.projects for delete
  using (auth.role() = 'authenticated');
